from typing import TypedDict, List, Optional


class AgentState(TypedDict):
    """Full state for the autonomous AI agent — EVN QA Workflow."""

    # === Core ===
    model_name: str                    # Legacy: single model name (kept for backward compat)
    goal: str                          # User's goal / task description
    url: Optional[str]                 # Initial URL to open (cleared after first use)
    base_url: Optional[str]            # Domain root (for safety guard)

    # === Dynamic Model Config (EVN QA) ===
    model_config: dict                 # {"brain_model": "...", "eval_model": "..."}
    #   brain_model → used by Manager Node (execution, planning, UI actions)
    #   eval_model  → used by Scoping, Validator, Reporter Nodes

    # === QA Scoping (EVN QA) ===
    test_scope: dict                   # {"ui": True, "functional": True, "security": True, "viewport": "pc"}
    test_case_data: Optional[dict]     # {"steps": [...], "expected_results": {...}, "preconditions": "..."}
    #   If None → Validator falls back to common-sense inference (Option B)

    # === Validation (EVN QA) ===
    validation_results: List[dict]     # [{"step": "...", "actual": "...", "expected": "...", "passed": bool, "severity": "..."}]
    is_bug: bool                       # True if Validator detected a failure in the latest check
    severity: Optional[str]           # "Critical" | "Major" | "Minor" | "Trivial" — latest bug severity

    # === Perception ===
    screenshot: Optional[str]          # Current screenshot (base64 JPEG)
    dom_elements: Optional[list]       # Raw DOM elements from dom_tool

    # === Decision ===
    next_action: Optional[dict]        # Tool calls from AI: {"tool_calls": [...]}
    messages: List[dict]               # ReAct conversation history (JSON messages)

    # === Output ===
    history: List[str]                 # Human-readable action log (for UI)
    findings: List[dict]               # Bug reports [{title, description, severity, url}]
    last_thought: Optional[str]        # Latest AI thought (for UI display)
    task_plan: List[dict]              # Dynamic steps: [{"step": "...", "status": "todo|done|failed"}]
    final_report: Optional[dict]       # Structured report generated by Reporter Node

    # === Control ===
    is_complete: bool                  # Whether the task is done
    last_action_location: Optional[dict]  # Cursor position for screenshot overlay
    current_step_count: int            # Incremented each Manager→Action cycle (for max_steps guard)
    max_steps: int                     # Hard cap on cycles (default: 50)

    # === Auth ===
    login_user: Optional[str]          # Login username (if provided)
    login_pass: Optional[str]          # Login password (if provided)

    # === Internal Counters (kept across graph loops) ===
    _api_error_count: int              # Consecutive API errors (stop when >= 2)
    _empty_count: int                  # Consecutive empty responses
    _last_actions: List[str]           # Recent action IDs (anti-loop detection)

